# Generated by Django 4.0.1 on 2022-02-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_num',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
    ]
