# Generated by Django 4.0.1 on 2022-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_alter_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%Y/%m/%d/', verbose_name='Видео'),
        ),
    ]
