# Generated by Django 4.0.1 on 2022-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_category_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.CharField(default='', max_length=150, verbose_name='Курстун автору'),
            preserve_default=False,
        ),
    ]
